services:
  postgres:
    container_name: postgres-sql-retour
    image: postgres
    environment:
      POSTGRES_USER: Retours_client
      POSTGRES_PASSWORD: rihab
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: Retours_client
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped
  keycloak:
    container_name: keycloak-Retours-client
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Admin
    volumes:
      - ./keycloak/realm/Retours-client.json:/opt/keycloak/data/import/Retours-client.json
    command: "start-dev --import-realm"
    networks:
      - spring-demo
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local